### ISSUE TITLE
Unintended changes

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/boutproject.github.io#76]
Could someone review this?
I meant to open a PR, but changed directly, sorry.

https://github.com/boutproject/boutproject.github.io/commit/f09c49d9cde8921e979a9071b0ca8996401f5db3

I could also revert and open a PR, if that is easier ...

**Comment by ZedThree** [comment]
Yes, that's a better name but unfortunately the readthedocs link doesn't work because L31 in `_includes/header.html` prepends the website url: 
https://github.com/boutproject/boutproject.github.io/blob/f09c49d9cde8921e979a9071b0ca8996401f5db3/_includes/header.html#L31

We'll need to add some logic there to detect absolute urls and not prepend in that case, but I'm not sure how to do that off the top of my head. Please could you revert for now and make a PR?

Maybe also rename the (current) `documentation` page title to `getting help`?

**Comment by dschwoerer** [comment]
Thanks :+1: 
I'll have a look at getting a proper fix in
